import { test, expect } from '@playwright/test';

test.describe('InkForge Main Flow', () => {
  test('Complete setup wizard and publish a post', async ({ page }) => {
    // 1. 访问安装向导
    await page.goto('/setup');
    
    // 等待加载状态结束
    await expect(page.locator('text=完成首次安装')).toBeVisible();

    // 2. 填写表单
    await page.fill('input[placeholder="InkForge"]', 'E2E Test Site');
    await page.fill('input[placeholder="http://localhost:2000"]', 'http://127.0.0.1:2002');
    
    // admin URL 自动推导，直接填写管理员信息
    await page.fill('input[placeholder="admin"]', 'e2e_admin');
    await page.fill('input[placeholder="admin@example.com"]', 'admin@example.com');
    await page.fill('input[placeholder="******"]', 'password123');
    
    // 提交安装
    await page.click('button[type="submit"]');
    
    // 3. 验证安装完成并跳转后台
    await expect(page.locator('text=安装完成')).toBeVisible();
    await page.click('button:has-text("立即进入后台")');
    
    // 这里如果直接重定向到了后台，或者是登录页
    // 如果后台未登录，填写登录信息 (取决于后端的 redirect)
    // 通常安装后 cookie 是自动种下的
    await expect(page.url()).toContain('/admin');
    
    // 4. 验证进入了 Dashboard (包含侧边栏，例如"文章")
    await expect(page.locator('a:has-text("文章")')).toBeVisible({ timeout: 10000 });
    
    // 5. 点击“新建文章”或进入文章列表并创建
    await page.click('a:has-text("文章")');
    await page.click('a:has-text("写文章")');
    
    // 6. 填写文章编辑器
    await page.fill('input[placeholder="请输入标题"]', 'My First E2E Post');
    // 编辑器可能是 contenteditable
    await page.locator('.ProseMirror').fill('This is the content of my first post generated by E2E test.');
    
    // 7. 点击发布
    await page.click('button:has-text("发 布")');
    
    // 8. 验证发布成功并回到列表，且能看到刚发布的文章
    await expect(page.locator('text=发布成功')).toBeVisible();
    await page.click('a:has-text("文章")');
    await expect(page.locator('text=My First E2E Post')).toBeVisible();
  });
});
