import sqlite3

DB = r'D:\InkForge\inkforge.db'
conn = sqlite3.connect(DB)
c = conn.cursor()

# Get hash from reset_temp_xyz (password = InkForge2026, generated by Rust)
c.execute("SELECT password_hash FROM users WHERE username='reset_temp_xyz'")
row = c.fetchone()
rust_hash = row[0]
print(f"Source: reset_temp_xyz hash params: {rust_hash.split('$')[3]}")

# Apply to admin
c.execute("UPDATE users SET password_hash = ? WHERE username = 'admin'", (rust_hash,))
conn.commit()
print("Updated admin -> password = InkForge2026")

# Cleanup all temp accounts
for name in ['testuser', 'tempreset', '__temp_admin_reset__', 'reset_temp_xyz']:
    c.execute("DELETE FROM users WHERE username=?", (name,))
conn.commit()
print("Cleaned up temp accounts")

# Verify
c.execute("SELECT username, substr(password_hash, 0, 55), status FROM users")
print("\n=== Final Users ===")
for r in c.fetchall():
    print(f"  {r[0]} | {r[1]}... | {r[2]}")

conn.close()
print("\n*** LOGIN: admin / InkForge2026 ***")
